# -*- coding: utf-8 -*-
"""ScraperFakeJob.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nIF80Fh6wFRV9OPDB3aRcoL-pA98ynt0
"""

import requests
from bs4 import BeautifulSoup
import csv

# URL website
URL = "https://realpython.github.io/fake-jobs/"

# Mengambil halaman website
response = requests.get(URL)

# Cek apakah request berhasil
if response.status_code == 200:
    print("Website berhasil diakses")
else:
    print("Gagal mengakses website")
    exit()

# Parsing HTML
soup = BeautifulSoup(response.text, "html.parser")

# Mencari semua job card
job_cards = soup.find_all("div", class_="card-content")

# List untuk menyimpan hasil
jobs_data = []

# Loop setiap job
for job in job_cards:

    # Mengambil title
    title_tag = job.find("h2", class_="title")
    title = title_tag.text.strip() if title_tag else "N/A"

    # Mengambil company
    company_tag = job.find("h3", class_="company")
    company = company_tag.text.strip() if company_tag else "N/A"

    # Mengambil location
    location_tag = job.find("p", class_="location")
    location = location_tag.text.strip() if location_tag else "N/A"

    # Mengambil link detail job
    link_tag = job.find_next("a", string="Apply")

    if link_tag and link_tag.get("href"):
        detail_url = URL + link_tag["href"]
    else:
        detail_url = "N/A"

    # Menyimpan ke list
    jobs_data.append([
        title,
        company,
        location,
        detail_url
    ])

# Menyimpan ke CSV
with open("jobs.csv", mode="w", newline="", encoding="utf-8") as file:
    writer = csv.writer(file)

    # Header CSV
    writer.writerow([
        "Job Title",
        "Company",
        "Location",
        "Detail URL"
    ])

    # Isi data
    writer.writerows(jobs_data)

print(f"Berhasil menyimpan {len(jobs_data)} data ke jobs.csv")